services:
  api:
    image: node:20-alpine
    container_name: agente_nfe_api
    working_dir: /app
    command: sh -c "npm install && npm run prisma:generate && npm --workspace @app/api run dev"
    env_file:
      - ./apps/api/.env
    volumes:
      - ./:/app
      - api_node_modules:/app/node_modules
    ports:
      - "3333:3333"

  web:
    image: node:20-alpine
    container_name: agente_nfe_web
    working_dir: /app
    command: sh -c "npm install && npm --workspace @app/web run dev -- --host 0.0.0.0 --port 5173"
    env_file:
      - ./apps/web/.env
    volumes:
      - ./:/app
      - web_node_modules:/app/node_modules
    depends_on:
      - api
    ports:
      - "5173:5173"

  worker:
    image: node:20-alpine
    container_name: agente_nfe_worker
    working_dir: /app
    command: sh -c "npm install && npm run prisma:generate && npm --workspace @app/api run dev:worker"
    env_file:
      - ./apps/api/.env
    volumes:
      - ./:/app
      - worker_node_modules:/app/node_modules
    depends_on:
      - api

volumes:
  api_node_modules:
  web_node_modules:
  worker_node_modules:
